In [1]:
pip install IPython

Note: you may need to restart the kernel to use updated packages.


In [2]:
# 주피터노트북 셀 스타일 조절
from IPython.display import display, HTML
# 셀 컨테이너의 너비를 100%로 설정
display(HTML("<style>.container { width: 100% !important; }</style>"))

## 인공지능까지 이어진대. I/O Numpy를 반드시 이해해야함.
다차원 배열? 차원. 현실세계에 데이터를 어떻게 표현할 것인가?
문자를 숫자로 표현하려면 어떻게 해야할까? 이미지를 데이터화 하려면 어떻게 해야할까?
이걸 해결하는 것이 차원이라고 한다. 3가지 차원을 이야기한다.
1차원 array는 vector라고 한다. vector에는 특징이 하나 있다. 방향성이 있다.
방향을 가지고 있다. 일방향을 표현하는 것이 vector이다.
X좌표만 있는것이 1차원 데이터이다.
2차원 데이터는 MATRIX라고 부른다. X, Y가 있다.
3차원은 텐서라고 부른다. X, Y, Z좌표를 가지고 있다.
데이터가 하나만 있을때는 Scalar라고 부른다. - MATRIX - TENSOR 이렇게 진화
shape는 모양을 의미한다. 
SCALAR의 X는 방향이라고 알아야한다. 실제로 표현할때에는 Column으로 표현한다.
2D는 열, 행이 있어서 데이터가 쌓일때 위에서 아래로 쌓인다
연산이 요소별 연산이 이루어진다는것. 

In [3]:
import numpy as np
np.__version__

'1.26.4'

## Numpy 배열 이해하기

## ndim(demention, rank)

In [4]:
a = np.array(0)
a, a.ndim, type(a)

(array(0), 0, numpy.ndarray)

In [5]:
a = np.array([2, 4, 6])
a, a.ndim, type(a) #차원을 의미하기에 '1'이라고 찍혔다

(array([2, 4, 6]), 1, numpy.ndarray)

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [7]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [5, 5, 6]]])
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [5, 5, 6]]]),
 3,
 numpy.ndarray)

In [8]:
a.shape

(2, 2, 3)

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [9]:
a = np.array(3)
a, a.shape # 행렬아님

(array(3), ())

In [10]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [12]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

## 넘파이 배열
리스트를 넘파이 배열로 생성 np.array(리스트)
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [13]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [14]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [15]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [16]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [17]:
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [18]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [ ]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

In [ ]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

In [ ]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

## https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다

In [ ]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

In [ ]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

In [ ]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [ ]:
np.exp(-np.inf)

## 기술통계

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [ ]:
x.mean()

In [ ]:
np.mean(x)

In [ ]:
np.var(x)  # 분산

In [ ]:
np.std(x)  # 표준 편차

In [ ]:
np.max(x)  # 최댓값


In [ ]:
np.min(x)  # 최소값


## 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [ ]:
np.percentile(x, 0)  # 최소값


In [ ]:
np.percentile(x, 25)  # 1사분위 수


In [ ]:
np.percentile(x, 50)  # 2사분위 수


In [ ]:
np.percentile(x, 75)  # 3사분위 수


In [ ]:
np.percentile(x, 100)  # 최댓값


## 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소

In [ ]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 

In [ ]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

In [ ]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

In [ ]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

In [ ]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

In [ ]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

In [ ]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

In [ ]:
print(np.arange(2, 20, 2), type(np.arange(2, 20,2)))

In [ ]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

## reshape 구조의 재배열
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.

In [ ]:
arr, arr.ndim, arr.shape


In [ ]:
arr = arr.reshape(10,5)
arr, arr.ndim, arr.shape


In [ ]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape


In [ ]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

In [ ]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

In [ ]:
print(np.arange(2,101,2).reshape(5,10))

In [ ]:
np.arange(1, 31)

In [ ]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

In [ ]:
arr4 = np.arange(1, 31).reshape(-1, 2)
arr4, arr4.ndim, arr4.shape

In [ ]:
np.arange(1, 21).reshape(5, 4)

In [ ]:
print(np.arange(1,21).reshape(5,-1))

In [ ]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

In [ ]:
# 5개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(-1, 5)
# rehsape -1은, 행무관하고 n개의 컬럼을 만든다

In [ ]:
# 사이즈가 맞아야 한다.
np.arange(1, 21).reshape(-1, 7)

In [ ]:
a = np.arange(12)
a, a.shape

In [ ]:
# 원본 값이 바뀜
a.shape = 3, -1
a, a.shape

In [ ]:
a.shape = -1, 1
a, a.shape

## 넘파이배열의 자료형 형변환
배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32

In [ ]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

In [ ]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 정수형 => 문자열
matrix.astype('<U5')

In [ ]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

In [ ]:
# 불린 -> 정수
matrix2.astype(int)

In [ ]:
# 불린형 -> 문자열
matrix2.astype('<U5')

In [ ]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

In [ ]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

## 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[0]


In [ ]:
a[2]


In [ ]:
a[[0, 2, 4]]

In [ ]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

In [ ]:
a[b]

In [ ]:
a[2] = 0
a

## 인덱싱 슬라이싱
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

## 넘파이배열 슬라이싱
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원

넘파이배열[행, 열] = [start:end:step, start2:end2:step2]

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[:]


In [ ]:
 a[1:]


In [ ]:
a[-1:]


In [ ]:
a[:3]


In [ ]:
a[:-1]


In [ ]:
a[1:4]


In [ ]:
a = np.arange(10)
a

In [ ]:
a = np.arange(10)
a[1::2]

In [ ]:
a = np.arange(10)
a[::-1]

### 2D array

In [ ]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:
a[-1, -1]

In [ ]:
a[1:]

In [ ]:
a[:-3]

In [ ]:
a[:]

In [ ]:
a[1:-1]

In [ ]:
a[:,:]

In [ ]:
a[:,1:]

In [ ]:
a[:, 4:]

In [ ]:
a[:, -1:]

In [ ]:
a[1:, 2:3]

In [ ]:
a[:2, 1:4]
a[:-1, 1:-1]

In [ ]:
a[1, 2]

In [ ]:
import numpy as np
b= np.array([[3]])
print(b.shape)
print(b.ndim)

In [ ]:
a = np.arange(15).reshape(3, -1)
a

In [ ]:
a[1] = [1, 3, 5, 7, 9]
a

## 전치행렬

In [ ]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

In [ ]:
# 2행 3열로 변환
print(matrix_d.T) #transpose

In [ ]:
# reshape과 transpose은 값이 다름을 유의
print(matrix_d.reshape(2,3)) #flatten이 선행되는 reshape
# 구조를 바꾸기 위해서 쫙 펴주고, 다시 그걸 재구성하는 형태이기 때문이다

In [ ]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

In [ ]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5)) #구조를 줄 수 있다. Numpy의 특징. 기본적으로 행열 개념이 있기 때문이다

## 섞기

In [19]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[5 1 3 4 2]


In [22]:
import numpy as np

# 원본 배열
arr = np.array([1, 2, 3, 4, 5])

# np.random.shuffle
np.random.shuffle(arr)
print("Shuffled (in-place):", arr)

# np.random.permutation
arr = np.array([1, 2, 3, 4, 5])
shuffled_arr = np.random.permutation(arr)
print("Original:", arr)
print("Permutation:", shuffled_arr)

# reshape
original = np.arange(1, 13)
reshaped = original.reshape(3, 4)
print("Original array:")
print(original)
print("Reshaped array:")
print(reshaped)

# matrix_d.T
matrix_d = np.array([[1, 2, 3], [4, 5, 6]])
transposed = matrix_d.T
print("Original matrix:")
print(matrix_d)
print("Transposed matrix:")
print(transposed)


Shuffled (in-place): [5 3 1 4 2]
Original: [1 2 3 4 5]
Permutation: [2 1 5 3 4]
Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Original matrix:
[[1 2 3]
 [4 5 6]]
Transposed matrix:
[[1 4]
 [2 5]
 [3 6]]


In [31]:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(matrix)
print(matrix)  # 행이 무작위로 섞임, 열은 그대로

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11)
matrix_e

In [ ]:
np.random.shuffle(matrix_e)
matrix_e

In [ ]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

In [ ]:
np.random.randint(1,46,6)

In [35]:
lotto= np.arange(1, 46)

np.random.shuffle(lotto)

lotto[:6]

array([12, 34, 40, 14, 19,  1])

In [49]:
a = np.arange(1,46)
np.random.seed(123)
np.random.shuffle(a)

a[:6]

array([ 9, 12, 28, 31, 19, 14])

In [50]:
a = np.arange(1,46)
np.random.seed(124)
np.random.shuffle(a)

a[:6]

array([34, 32, 42, 35, 24, 16])

In [51]:
a = np.arange(1,46)
np.random.seed(123)
np.random.shuffle(a)

a[:6]

array([ 9, 12, 28, 31, 19, 14])

In [41]:
np.random.randint(1, 46, 6)

array([ 3, 25, 28,  5, 21,  8])

## 실수 난수 뽑기

In [44]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

array([-0.52616596,  0.08185979,  0.64338169, -0.52619876,  2.41146705,
       -1.01305803,  1.55122901,  0.39544848,  0.93869697,  0.57193557])

In [42]:
matrix2 = np.random.randn(4, 4)
matrix2

array([[ 0.70676632, -0.865555  ,  1.40418861, -0.21914846],
       [-0.0491101 ,  0.16141706, -0.26839665, -0.9105824 ],
       [ 0.35681942, -1.08959682,  1.71852703, -0.0631444 ],
       [ 1.0543843 , -0.01368721,  1.16498737, -1.04751292]])

In [45]:
matrix1.max(), matrix1.min()

(2.411467048720304, -1.0130580346322664)

In [ ]:
matrix2 = np.random.choice?

## 집계함수에서의 축

In [52]:
m1 = np.random.randint(1, 50, (5,5))
m1

array([[ 4, 43,  6,  1, 12],
       [35, 11, 23, 14, 19],
       [37, 16, 44, 28, 45],
       [31,  7, 46, 27, 17],
       [ 7, 15, 40, 12,  8]])

In [53]:
np.sum(m1, axis=0) # (x)열 합계 로 고쳐서 외우는게 나을듯

array([114,  92, 159,  82, 101])

In [54]:
np.sum(m1, axis=1) # (y)행 합계

array([ 66, 102, 170, 128,  82])

In [57]:
# 1번째행의 합계는
np.sum(m1[0,:])

66

In [58]:
# 1번째행의 합계는
np.sum(m1[0,:], axis=0) # x축(행 방향) 합계

66

In [59]:
np.sum(m1[0,:], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
m1[2, : ]
np.sum(m1[ : ,2 ], axis=0)

## np.sort()

In [60]:
import numpy as np

arr = np.array([3, 1, 2, 4, 5])
sorted_arr = np.sort(arr)
print("원본 배열:", arr)
print("정렬된 배열:", sorted_arr)


원본 배열: [3 1 2 4 5]
정렬된 배열: [1 2 3 4 5]


In [61]:
import numpy as np

arr = np.array([[3, 1, 2], [4, 5, 0]])
sorted_arr = np.sort(arr, axis=1)  # 각 행을 정렬
print("원본 배열:")
print(arr)
print("각 행을 정렬한 배열:")
print(sorted_arr)

sorted_arr = np.sort(arr, axis=0)  # 각 열을 정렬
print("각 열을 정렬한 배열:")
print(sorted_arr)

원본 배열:
[[3 1 2]
 [4 5 0]]
각 행을 정렬한 배열:
[[1 2 3]
 [0 4 5]]
각 열을 정렬한 배열:
[[3 1 0]
 [4 5 2]]


In [62]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3))
m2

array([[ 2, 44, 38],
       [26, 21, 13],
       [19, 18,  2],
       [45, 42, 49]])

In [63]:
np.sort(m2)

array([[ 2, 38, 44],
       [13, 21, 26],
       [ 2, 18, 19],
       [42, 45, 49]])

In [64]:
np.sort(m2, axis=0)

array([[ 2, 18,  2],
       [19, 21, 13],
       [26, 42, 38],
       [45, 44, 49]])

In [65]:
m2[::-1, ::] # 행전체가 역순으로 바뀌는 것과는 다르다

array([[45, 42, 49],
       [19, 18,  2],
       [26, 21, 13],
       [ 2, 44, 38]])

In [66]:
import numpy as np

m1 = np.random.randint(1, 50, (5, 5))
print("원본 배열 m1:")
print(m1)


원본 배열 m1:
[[28 23  4  4 12]
 [22 26 40 42 35]
 [ 4 12  4 31  7]
 [10 24 15 39 20]
 [ 7 13 28 39 18]]


In [67]:
sum_by_columns = np.sum(m1, axis=0)
print("\n열별 합계 (axis=0):")
print(sum_by_columns)


열별 합계 (axis=0):
[ 71  98  91 155  92]


In [68]:
sum_by_rows = np.sum(m1, axis=1)
print("\n행별 합계 (axis=1):")
print(sum_by_rows)



행별 합계 (axis=1):
[ 71 165  58 108 105]


In [69]:
m2 = np.random.randint(1, 50, (4, 3))
print("원본 배열 m2:")
print(m2)


원본 배열 m2:
[[47 11 36]
 [36  2 48]
 [46 17  6]
 [41 46 23]]


In [70]:
sorted_by_rows = np.sort(m2, axis=1)
print("\n각 행을 따라 오름차순 정렬 (axis=1):")
print(sorted_by_rows)



각 행을 따라 오름차순 정렬 (axis=1):
[[11 36 47]
 [ 2 36 48]
 [ 6 17 46]
 [23 41 46]]


In [71]:
sorted_by_columns = np.sort(m2, axis=0)
print("\n각 열을 따라 오름차순 정렬 (axis=0):")
print(sorted_by_columns)



각 열을 따라 오름차순 정렬 (axis=0):
[[36  2  6]
 [41 11 23]
 [46 17 36]
 [47 46 48]]


## 인덱스 소팅

In [ ]:
x = np.array([9,5,4])
np.argsort(x)

In [ ]:
x[np.argsort(x)]

In [ ]:
m4 = np.arange(1,10).reshape(3,3)
m4

In [ ]:
np.insert(m4, 0, 100)

In [ ]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=1)

In [72]:
m4 = np.arange(1,10).reshape(3,3)
m4.shape, m4.shape[1], len(m4)

((3, 3), 3, 3)

In [77]:
m5 = np.arange(1,21).reshape(4,5)
np.insert(m5, m5.shape[1], [100,200,300,400], axis=1)

array([[  1,   2,   3,   4,   5, 100],
       [  6,   7,   8,   9,  10, 200],
       [ 11,  12,  13,  14,  15, 300],
       [ 16,  17,  18,  19,  20, 400]])

## boolean indexing, mask

In [ ]:
matrix = np.arange(1, 21)
matrix

In [ ]:
matrix > 10

In [ ]:
matrix[matrix > 10]

In [ ]:
(matrix > 10).sum()

## Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [ ]:
matrix = np.random.randint(1, 100, 30)
matrix[(matrix > 30) &  (matrix < 70)]
matrix

In [ ]:
num = np.random.randint(1,100,30)
num, num[(num > 30) & (num < 70)]

In [91]:
# ~ 은 reverse를 의미
num[~(num > 30) & (num < 70)]

array([ 3, 19, 19, 12, 27, 11,  4, 24, 26, 28])

In [ ]:
num[(num < 10) | (num > 90)]

In [92]:
num1 = np.random.randint(1, 101, 30)
num1[(num1 > 30) & (num1 < 70)]

array([51, 37, 45, 62, 63, 50, 33, 40, 36])

In [93]:
num1[~(num1 > 30) & (num1 < 70)]


array([15, 24, 29, 25, 16,  5, 22,  2])

## fancy indexing

In [ ]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

## np.where()

In [ ]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)

In [ ]:
b = np.arange(20, 31)
b, np.where(b<25)